### ISSUE TITLE
Failed to resolve: com.github.Piashsarker:AndroidAppUpdateLibrary:1.0.4

### ISSUE THREAD

**Issue by EdgardLevy** [Piashsarker/AndroidAppUpdateLibrary#18]
I followed the instructions, but i received this gradle build error

Failed to resolve: com.github.Piashsarker:AndroidAppUpdateLibrary:1.0.4

**Comment by Piashsarker** [comment]
![image](https://user-images.githubusercontent.com/8473499/135288424-6b7dca18-dcc8-4e45-a5f4-ffda1c195feb.png)

Working fine for me. 
Did you add the below line in project-level `build.gradle `
```
allprojects {
    repositories {
        maven { url "https://jitpack.io" }
    }
}
```
Provide a full logcat if possible. Thanks

**Comment by EdgardLevy** [comment]
Now, it's works :-)

i made this change in settings.gradle

dependencyResolutionManagement{
  repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
  repositories{
    google()mavenCentral()maven{
      url'https://jitpack.io'
    }
  }
}
