### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by nowfalsalahudeen** [Piashsarker/AndroidAppUpdateLibrary#2]
Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference

**Comment by Piashsarker** [comment]
Did you add the Provider in the res => xml  folder with the specific name ?

**Comment by nowfalsalahudeen** [comment]
i already put this.. found on your code

    external-path name="external_files" path="."

**Comment by Piashsarker** [comment]
Create a folder called xml in res folder. Create a xml file and named it provider_paths. Paste below code:

<?xml version="1.0" encoding="utf-8"?>
  <paths xmlns:android="http://schemas.android.com/apk/res/android">
    <external-path name="external_files" path="."/>
  </paths>

**Comment by nowfalsalahudeen** [comment]
yep i already did that..but didnt worked..file downloaded successfully.after that this error occurs

**Comment by nowfalsalahudeen** [comment]
![screenshot from 2018-01-17 11-47-17](https://user-images.githubusercontent.com/4261741/35028470-374e56d6-fb7c-11e7-800c-e99424e4f163.png)

**Comment by nowfalsalahudeen** [comment]
Sory bro ..it was my mistake.i just forgot to update  manifest file

**Comment by Piashsarker** [comment]
Add below code in your manifest.xml file .
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.dcastalia.localapkupdatelibrary">

    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <application
        ..........................................................
        <provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="${applicationId}.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths"/>
        </provider>


    </application>

</manifest>```

**Comment by Piashsarker** [comment]
Thanks @nowfalsalahudeen  , I am closing the issue as it's fixed . Happy Coding.

**Comment by neethuantony42** [comment]
Hi @Piashsarker ,
I have used the code to update the app but i could only download the app in server but when i tried to install the same i am getting the error App not install.
Could you please help to solve the issue.

Thanks and Regards,
Neethu

**Comment by Piashsarker** [comment]
@neethuantony42  
Can you please share the logcat or Screenshot.
