### ISSUE TITLE
Permission required for Android 8

### ISSUE THREAD

**Issue by alihusseinalissa** [Piashsarker/AndroidAppUpdateLibrary#4]
On Android 8 Oreo (API 26) the downloaded apk file is not installed automatically, you should add required permission of install APK files, so add this permission into the manifest file to run on Android 8 properly:

"android.permission.REQUEST_INSTALL_PACKAGES"

**Comment by Piashsarker** [comment]
Thanks for your issue. Please see the latest version of the library.  Now automatically install will work in Android Oreo.
