### ISSUE TITLE
Downloads not successful

### ISSUE THREAD

**Issue by cyb3rko** [Piashsarker/AndroidAppUpdateLibrary#7]
Currently downloads do not work.
I used the sample app and after clicking download it shows the toast "Error: Try Again".

Android: 8.0.0

It seems like it's the problem of OkHTTP:

![image](https://user-images.githubusercontent.com/46033730/101990076-e89f7700-3ca4-11eb-9d44-3099195864cf.png)

It throws a FileNotFoundExeception even though it does exist. If you click the link ion the logs you can simply download it.

**Comment by cyb3rko** [comment]
@Piashsarker Are you planning to rewrite it to Kotlin? I think I could do that quickly (hopefully).

**Comment by Piashsarker** [comment]
Clone this project and create another branch. Add speerate kotlin folder
module, and create a PR.  Thanks

**Comment by cyb3rko** [comment]
So parallel to module "appupdatelibrary" I shall add the new module "appupdatelibrarykt"?

**Comment by Piashsarker** [comment]
Yes, that is correct.

**Comment by cyb3rko** [comment]
Ok, gonna work on it
