### ISSUE TITLE
Download goes into minus

### ISSUE THREAD

**Issue by MudassirMobi** [Piashsarker/AndroidAppUpdateLibrary#9]
While  downloading the update ,download goes till 50% or 65% and then goes into minus like -65% and decreases to 0 again.

**Comment by Piashsarker** [comment]
thanks for your issue, will look into it.

**Comment by cyb3rko** [comment]
@MudassirMobi Did you just download the original library code and test it in the sample app?

**Comment by MudassirMobi** [comment]
@cyb3rko Let me do the same .

**Comment by MudassirMobi** [comment]
As per your suggestion I downloaded the demo project from GitHub and added
my apk url but issue still persists. I have attached the screenshot for
your reference.

It's showing positive value till 65 and then it decreases to 0 like -65
,-64.....-1,0.

**Comment by cyb3rko** [comment]
Hmm, weird.
Does the download fail or does it download?
I will have to try to implement the library in an own app because since now I just worked directly on the library code.

**Comment by MudassirMobi** [comment]
App was not working than  I have added this line of code in  Application tag in Manifest file 
" android:requestLegacyExternalStorage="true" " ,for android 10 in your project. And then it works, It gets download, but  the progress bar showing nagative values as well ,which is my main concern.

**Comment by cyb3rko** [comment]
Ah, so it was the problem with Android 10 okay.
Yeah, adding this line is the much easier way of installing apps on Android 10 or higher, but it's not good practice.
I have not tested it yet on Android 10, I will do it as well and see if I can solve that problem, thanks!

**Comment by cyb3rko** [comment]
At some point we will add installer for Android 10.

**Comment by MudassirMobi** [comment]
Cool, I m also looking to  solutions  for  the same .Lets fix this problem.

**Comment by cyb3rko** [comment]
I just added `System.out.println(progress[0]);` in ProgressUpdate of the AsyncTask and ran the app. It just prints out the numbers from 0 to 100.
For me everything seems to work. You can do it too and see what gets printed.

**Comment by MudassirMobi** [comment]
Yes,but i m running your project and this is logcat while running
2020-12-22 17:34:17.321 21849-21849/com.dcastalia.localapkupdatelibrary
E/Progress: Progress63%
2020-12-22 17:34:17.335 21849-21849/com.dcastalia.localapkupdatelibrary
E/Progress: Progress63%
2020-12-22 17:34:17.486 21849-21849/com.dcastalia.localapkupdatelibrary
E/Progress: Progress63%
2020-12-22 17:34:17.487 21849-21849/com.dcastalia.localapkupdatelibrary
E/Progress: Progress64%
2020-12-22 17:34:17.756 21849-21849/com.dcastalia.localapkupdatelibrary
E/Progress: Progress64%
2020-12-22 17:34:17.757 21849-21849/com.dcastalia.localapkupdatelibrary
E/Progress: Progress65%
2020-12-22 17:34:18.107 21849-21849/com.dcastalia.localapkupdatelibrary
E/Progress: Progress65%
2020-12-22 17:34:18.107 21849-21849/com.dcastalia.localapkupdatelibrary
E/Progress: Progress-65%
2020-12-22 17:34:18.390 21849-21849/com.dcastalia.localapkupdatelibrary
E/Progress: Progress-65%
2020-12-22 17:34:18.454 21849-21849/com.dcastalia.localapkupdatelibrary
E/Progress: Progress-65%
2020-12-22 17:34:18.540 21849-21849/com.dcastalia.localapkupdatelibrary
E/Progress: Progress-65%
2020-12-22 17:34:18.541 21849-21849/com.dcastalia.localapkupdatelibrary
E/Progress: Progress-64%
2020-12-22 17:34:19.021 21849-21849/com.dcastalia.localapkupdatelibrary
E/Progress: Progress-64%
2020-12-22 17:34:19.021 21849-21849/com.dcastalia.localapkupdatelibrary
E/Progress: Progress-63%
2020-12-22 17:34:19.461 21849-21849/com.dcastalia.localapkupdatelibrary
E/Progress: Progress-63%
2020-12-22 17:34:19.461 21849-21849/com.dcastalia.localapkupdatelibrary
E/Progress: Progress-62%
2020-12-22 17:34:20.107 21849-21849/com.dcastalia.localapkupdatelibrary
E/Progress: Progress-62%
2020-12-22 17:34:20.107 21849-21849/com.dcastalia.localapkupdatelibrary
E/Progress: Progress-61%
2020-12-22 17:34:20.363 21849-21849/com.dcastalia.localapkupdatelibrary
E/Progress: Progress-61%
2020-12-22 17:34:21.621 21849-21849/com.dcastalia.localapkupdatelibrary
E/Progress: Progress-61%
2020-12-22 17:34:21.639 21849-21849/com.dcastalia.localapkupdatelibrary
E/Progress: Progress-61%
2020-12-22 17:34:21.639 21849-21849/com.dcastalia.localapkupdatelibrary
E/Progress: Progress-60%

**Comment by MudassirMobi** [comment]
Can u mail a zip file of project on which you are testing?

**Comment by cyb3rko** [comment]
That's very weird.
I'm just using the code from the master branch.
I also added a Kotlin version of this library (#10), this code also works.

**Comment by MudassirMobi** [comment]
Thanks, I'll check it out.

**Comment by cyb3rko** [comment]
Does it try to install the app or does it not trigger the installation process?

**Comment by MudassirMobi** [comment]
It tries and it download also.
The link you provided for apk is from github or from server?

**Comment by cyb3rko** [comment]
The problem why the installation fails is because the update is on the same version so you can't update it so I built a new apk:
https://cdn.cyb3rko.de/Apps/testUpdate.apk

**Comment by MudassirMobi** [comment]
It worked. This apk is already stored on server OR stored on github ? while
you provide apk link for downloading in app.
Can u tell me  please.

**Comment by cyb3rko** [comment]
What worked? Was the progress shown or did the update succeed?
It's currently stored on my server.

**Comment by MudassirMobi** [comment]
Both worked. progress and  download as well,While i m using your apk link
in given sample app.
But when I provide my apk link in your sample app then download succeed but
progress bar not working properly.

**Comment by cyb3rko** [comment]
I think I will try using the DownloadManager and see if it works better. I'm gonna open a new branch in my forked repo.
I will notify you here if I did it.

**Comment by MudassirMobi** [comment]
Cool,Thanks .

**Comment by MudassirMobi** [comment]
Bro it worked ,progress bar showing all positive values till 100 by
changing this in your code

     // int total_size = c.getContentLength();//size of apk
                float total_size = c.getContentLength();//size of apk
                Log.e("apk length","total_size" + total_size);


                byte[] buffer = new byte[1024];
//                int len1 = 0;
//                int per = 0;
//                int downloaded=0;
                int len1 = 0;
                float per = 0;
                float downloaded=0;
                while ((len1 = is.read(buffer)) != -1) {
                    fos.write(buffer, 0, len1);
                    downloaded +=len1;
//                   per = (int) (downloaded * 100 / total_size);
                    per =  downloaded * 100 / total_size;
                    Log.e("publishprecess","Percent"+per);
                    int Percent = (int) (per) ;
//
                        publishProgress(Percent);
                        Log.e("publishprecess","Percent"+per);

Changing data types of calculating variables..

**Comment by MudassirMobi** [comment]
Thanxx for your help.

**Comment by cyb3rko** [comment]
Awesome. Then just open a pull request to fix it for others too.

**Comment by cyb3rko** [comment]
@MudassirMobi Or should I do that?

**Comment by MudassirMobi** [comment]
Yes, you can do that,if u can .it's just small changes

**Comment by cyb3rko** [comment]
@MudassirMobi I hope my fix works (see #11)

**Comment by MudassirMobi** [comment]
Yes ,but  I will be available on Monday or Tuesday so than I can
